version: 2
updates:
  # 监控 pnpm 依赖更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "peterCao22"
    assignees:
      - "peterCao22"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

  # 监控 API 应用依赖
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "peterCao22"
    commit-message:
      prefix: "chore(api)"
    labels:
      - "dependencies"
      - "api"

  # 监控 Web 应用依赖
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "peterCao22"
    commit-message:
      prefix: "chore(web)"
    labels:
      - "dependencies"
      - "frontend"

  # 监控数据库包依赖
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "peterCao22"
    commit-message:
      prefix: "chore(database)"
    labels:
      - "dependencies"
      - "database"

  # 监控 UI 包依赖
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "peterCao22"
    commit-message:
      prefix: "chore(ui)"
    labels:
      - "dependencies"
      - "ui"

  # 监控 Docker 镜像更新
  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "peterCao22"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  # 监控 GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "peterCao22"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "ci/cd"
